import type { Metadata } from 'next';
import robotoSans from './fonts';
import Providers from './lib/tanstackQueryProvider';
import StoreProvider from './lib/StoreProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${robotoSans.variable}`}>
                <Providers>
                    <StoreProvider>{children}</StoreProvider>
                </Providers>
            </body>
        </html>
    );
}
