import type { Metadata } from 'next';
import robotoSans from './fonts';

import Header from '@/features/components/Header/Header';
import Footer from '@/features/components/Footer/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${robotoSans.variable}`}>
                <Header />
                {children}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
