import type { Metadata } from 'next';
import robotoSans from './fonts';

// import { QueryClientProvider } from '@tanstack/react-query';
// import { queryClient } from '@/features/api/query-client';
import Providers from './lib/tanstackQueryProvider';
import StoreProvider from './lib/StoreProvider';
import Header from '@/features/components/Header/Header';
import Footer from '@/features/components/Footer/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${robotoSans.variable}`}>
                <Providers>
                    <StoreProvider>
                        <Header />
                        {children}
                        <Footer />
                    </StoreProvider>
                </Providers>
            </body>
        </html>
    );
}
