// import type { Metadata } from 'next';
import Header from '@/features/components/Header/Header';
import Footer from '@/features/components/Footer/Footer';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    );
}
